/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package guilearn;

/**
 * GUI学习主界面，可以在这个界面中点击不同按钮学到不同知识
 *
 * @author wy521
 */
public class main extends javax.swing.JFrame {

    /**
     * Creates new form main
     */
    public main() {
        initComponents();
        //居中显示
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonFlowLayout = new javax.swing.JButton();
        jButtonBorderLayout = new javax.swing.JButton();
        jButtonGridLayout = new javax.swing.JButton();
        jButtonCardLayout = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("GUILearn");
        setLocation(new java.awt.Point(250, 250));

        jButtonFlowLayout.setText("FlowLayoutDemo");
        jButtonFlowLayout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonFlowLayoutActionPerformed(evt);
            }
        });

        jButtonBorderLayout.setText("BorderLayoutDemo");
        jButtonBorderLayout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBorderLayoutActionPerformed(evt);
            }
        });

        jButtonGridLayout.setText("GridLayoutDemo");
        jButtonGridLayout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonGridLayoutActionPerformed(evt);
            }
        });

        jButtonCardLayout.setLabel("CardLayoutDemo");
        jButtonCardLayout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCardLayoutActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonCardLayout)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButtonFlowLayout)
                        .addGap(57, 57, 57)
                        .addComponent(jButtonBorderLayout)
                        .addGap(50, 50, 50)
                        .addComponent(jButtonGridLayout)))
                .addContainerGap(51, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonFlowLayout)
                    .addComponent(jButtonBorderLayout)
                    .addComponent(jButtonGridLayout))
                .addGap(30, 30, 30)
                .addComponent(jButtonCardLayout)
                .addContainerGap(335, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonFlowLayoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonFlowLayoutActionPerformed
        FlowLayoutDemo demo = new FlowLayoutDemo();
        demo.setVisible(true);
        demo.setLocationRelativeTo(null);
    }//GEN-LAST:event_jButtonFlowLayoutActionPerformed

    private void jButtonBorderLayoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBorderLayoutActionPerformed
        BorderLayoutDemo demo = new BorderLayoutDemo();
        demo.setSize(400, 200);
        demo.setVisible(true);
        demo.setLocationRelativeTo(null);
    }//GEN-LAST:event_jButtonBorderLayoutActionPerformed

    private void jButtonGridLayoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonGridLayoutActionPerformed
        // DemoLaucher demo=  new DemoLaucher("guilearn.GridLayoutDemo");
        GridLayoutDemo gld = new GridLayoutDemo();
        gld.setLocationRelativeTo(null);
        gld.setVisible(true);
    }//GEN-LAST:event_jButtonGridLayoutActionPerformed

    private void jButtonCardLayoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCardLayoutActionPerformed
        CardLayoutDemo demo = new CardLayoutDemo();
        demo.setVisible(true);
        demo.setSize(400, 200);
        demo.setLocationRelativeTo(null);
    }//GEN-LAST:event_jButtonCardLayoutActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonBorderLayout;
    private javax.swing.JButton jButtonCardLayout;
    private javax.swing.JButton jButtonFlowLayout;
    private javax.swing.JButton jButtonGridLayout;
    // End of variables declaration//GEN-END:variables
}
