/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package guilearn;

/**
 * GUI学习主界面，可以在这个界面中点击不同按钮学到不同知识
 *
 * @author wy521
 */
public class main extends javax.swing.JFrame {

    /**
     * Creates new form main
     */
    public main() {
        initComponents();
        //居中显示
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonFlowLayout = new javax.swing.JButton();
        jButtonBorderLayout = new javax.swing.JButton();
        jButtonGridLayout = new javax.swing.JButton();
        jButtonCardLayout = new javax.swing.JButton();
        jButtonAdapter = new javax.swing.JButton();
        JButtonJIconLabel = new javax.swing.JButton();
        jButtonJTextField = new javax.swing.JButton();
        jButtonJCheckBox = new javax.swing.JButton();
        jButtonJRadioButton = new javax.swing.JButton();
        jButtonJComboBox = new javax.swing.JButton();
        JButtonJTabbedPane = new javax.swing.JButton();
        jButtonJScrollPane = new javax.swing.JButton();
        jButtonJTree = new javax.swing.JButton();
        jButtonJTable = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("GUILearn");
        setLocation(new java.awt.Point(250, 250));

        jButtonFlowLayout.setText("FlowLayoutDemo");
        jButtonFlowLayout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonFlowLayoutActionPerformed(evt);
            }
        });

        jButtonBorderLayout.setText("BorderLayoutDemo");
        jButtonBorderLayout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBorderLayoutActionPerformed(evt);
            }
        });

        jButtonGridLayout.setText("GridLayoutDemo");
        jButtonGridLayout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonGridLayoutActionPerformed(evt);
            }
        });

        jButtonCardLayout.setLabel("CardLayoutDemo");
        jButtonCardLayout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCardLayoutActionPerformed(evt);
            }
        });

        jButtonAdapter.setText("AdapterDemo");
        jButtonAdapter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAdapterActionPerformed(evt);
            }
        });

        JButtonJIconLabel.setText("JIconLabelDemo");
        JButtonJIconLabel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JButtonJIconLabelActionPerformed(evt);
            }
        });

        jButtonJTextField.setText("JTextFieldDemo");
        jButtonJTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonJTextFieldActionPerformed(evt);
            }
        });

        jButtonJCheckBox.setText("JCheckBoxDemo");
        jButtonJCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonJCheckBoxActionPerformed(evt);
            }
        });

        jButtonJRadioButton.setText("JRadioButtonDemo");
        jButtonJRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonJRadioButtonActionPerformed(evt);
            }
        });

        jButtonJComboBox.setText("JComboBoxDemo");
        jButtonJComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonJComboBoxActionPerformed(evt);
            }
        });

        JButtonJTabbedPane.setText("JTabbedPaneDemo");
        JButtonJTabbedPane.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JButtonJTabbedPaneActionPerformed(evt);
            }
        });

        jButtonJScrollPane.setText("JScrollPaneDemo");
        jButtonJScrollPane.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonJScrollPaneActionPerformed(evt);
            }
        });

        jButtonJTree.setText("JTreeDemo");
        jButtonJTree.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonJTreeActionPerformed(evt);
            }
        });

        jButtonJTable.setText("JTableDemo");
        jButtonJTable.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonJTableActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jButtonAdapter, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonCardLayout, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButtonFlowLayout)
                            .addComponent(JButtonJIconLabel)
                            .addComponent(jButtonJRadioButton)
                            .addComponent(jButtonJScrollPane))
                        .addGap(41, 41, 41)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButtonBorderLayout)
                            .addComponent(jButtonJTextField)
                            .addComponent(jButtonJComboBox)
                            .addComponent(jButtonJTree))
                        .addGap(50, 50, 50)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButtonJTable)
                            .addComponent(JButtonJTabbedPane)
                            .addComponent(jButtonJCheckBox)
                            .addComponent(jButtonGridLayout))))
                .addContainerGap(43, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonFlowLayout)
                    .addComponent(jButtonBorderLayout)
                    .addComponent(jButtonGridLayout))
                .addGap(30, 30, 30)
                .addComponent(jButtonCardLayout)
                .addGap(32, 32, 32)
                .addComponent(jButtonAdapter)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JButtonJIconLabel)
                    .addComponent(jButtonJTextField)
                    .addComponent(jButtonJCheckBox))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonJRadioButton)
                    .addComponent(jButtonJComboBox)
                    .addComponent(JButtonJTabbedPane))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonJScrollPane)
                    .addComponent(jButtonJTree)
                    .addComponent(jButtonJTable))
                .addContainerGap(141, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonFlowLayoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonFlowLayoutActionPerformed
        FlowLayoutDemo demo = new FlowLayoutDemo();
        demo.setVisible(true);
        demo.setLocationRelativeTo(null);
    }//GEN-LAST:event_jButtonFlowLayoutActionPerformed

    private void jButtonBorderLayoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBorderLayoutActionPerformed
        BorderLayoutDemo demo = new BorderLayoutDemo();
        demo.setSize(400, 200);
        demo.setVisible(true);
        demo.setLocationRelativeTo(null);
    }//GEN-LAST:event_jButtonBorderLayoutActionPerformed

    private void jButtonGridLayoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonGridLayoutActionPerformed
        // DemoLaucher demo=  new DemoLaucher("guilearn.GridLayoutDemo");
        GridLayoutDemo gld = new GridLayoutDemo();
        gld.setLocationRelativeTo(null);
        gld.setVisible(true);
    }//GEN-LAST:event_jButtonGridLayoutActionPerformed

    private void jButtonCardLayoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCardLayoutActionPerformed
        CardLayoutDemo demo = new CardLayoutDemo();
        demo.setVisible(true);
        demo.setSize(400, 200);
        demo.setLocationRelativeTo(null);
    }//GEN-LAST:event_jButtonCardLayoutActionPerformed

    private void jButtonAdapterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAdapterActionPerformed
        AdapterDemo adapterDemo = new AdapterDemo();
        adapterDemo.setVisible(true);
    }//GEN-LAST:event_jButtonAdapterActionPerformed

    private void JButtonJIconLabelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JButtonJIconLabelActionPerformed
        mainSwingJFrame main = new mainSwingJFrame();
        main.setVisible(true);
        JIconLabelDemo jIconLabelDemo = new JIconLabelDemo();
        main.add(jIconLabelDemo);
        jIconLabelDemo.setBounds(0, 0, 500, 500);
        jIconLabelDemo.setVisible(true);
    }//GEN-LAST:event_JButtonJIconLabelActionPerformed

    private void jButtonJTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonJTextFieldActionPerformed
        mainSwingJFrame main = new mainSwingJFrame();
        main.setVisible(true);
        JTextFieldDemo demo = new JTextFieldDemo();
        main.add(demo);
        demo.setBounds(0, 0, 500, 500);
        demo.setVisible(true);
    }//GEN-LAST:event_jButtonJTextFieldActionPerformed

    private void jButtonJCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonJCheckBoxActionPerformed
        mainSwingJFrame main = new mainSwingJFrame();
        main.setVisible(true);
        JCheckBoxDemo demo = new JCheckBoxDemo();
        main.add(demo);
        demo.setBounds(0, 0, 500, 500);
        demo.setVisible(true);
    }//GEN-LAST:event_jButtonJCheckBoxActionPerformed

    private void jButtonJRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonJRadioButtonActionPerformed
        mainSwingJFrame main = new mainSwingJFrame();
        main.setVisible(true);
        JRadioButtonDemo demo = new JRadioButtonDemo();
        main.add(demo);
        demo.setBounds(0, 0, 500, 500);
        demo.setVisible(true);
    }//GEN-LAST:event_jButtonJRadioButtonActionPerformed

    private void jButtonJComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonJComboBoxActionPerformed
       mainSwingJFrame main = new mainSwingJFrame();
        main.setVisible(true);
        JComboBoxDemo demo = new JComboBoxDemo();
        main.add(demo);
        demo.setBounds(0, 0, 500, 500);
        demo.setVisible(true);
    }//GEN-LAST:event_jButtonJComboBoxActionPerformed

    private void JButtonJTabbedPaneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JButtonJTabbedPaneActionPerformed
       mainSwingJFrame main = new mainSwingJFrame();
        main.setVisible(true);
        JTabbedPaneDemo demo=new JTabbedPaneDemo();
        main.add(demo);
        demo.setBounds(0, 0, 500, 500);
        demo.setVisible(true);
    }//GEN-LAST:event_JButtonJTabbedPaneActionPerformed

    private void jButtonJScrollPaneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonJScrollPaneActionPerformed
        mainSwingJFrame main = new mainSwingJFrame();
        main.setVisible(true);
        JScrollPaneDemo demo=new JScrollPaneDemo();
        main.add(demo);
        demo.setBounds(0, 0, 1000, 1000);
        demo.setVisible(true);
    }//GEN-LAST:event_jButtonJScrollPaneActionPerformed

    private void jButtonJTreeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonJTreeActionPerformed
        mainSwingJFrame main = new mainSwingJFrame();
        main.setVisible(true);
        JTreeDemo demo=new JTreeDemo();
        main.add(demo);
        demo.setBounds(0, 0, 1000, 1000);
        demo.setVisible(true);
    }//GEN-LAST:event_jButtonJTreeActionPerformed

    private void jButtonJTableActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonJTableActionPerformed
        mainSwingJFrame main = new mainSwingJFrame();
        main.setVisible(true);
        JTableDemo demo=new JTableDemo();
        main.add(demo);
        demo.setBounds(0, 0, 1000, 1000);
        demo.setVisible(true);
    }//GEN-LAST:event_jButtonJTableActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JButtonJIconLabel;
    private javax.swing.JButton JButtonJTabbedPane;
    private javax.swing.JButton jButtonAdapter;
    private javax.swing.JButton jButtonBorderLayout;
    private javax.swing.JButton jButtonCardLayout;
    private javax.swing.JButton jButtonFlowLayout;
    private javax.swing.JButton jButtonGridLayout;
    private javax.swing.JButton jButtonJCheckBox;
    private javax.swing.JButton jButtonJComboBox;
    private javax.swing.JButton jButtonJRadioButton;
    private javax.swing.JButton jButtonJScrollPane;
    private javax.swing.JButton jButtonJTable;
    private javax.swing.JButton jButtonJTextField;
    private javax.swing.JButton jButtonJTree;
    // End of variables declaration//GEN-END:variables
}
